<?php

$codeDay = date('w') ; //Obtenemos la clave del día (0-6)
$getDate = date('Y-m-d');

/** Historial de Asistencias */

$sql_attendance_records_b = "SELECT DISTINCT
        ATT.NOM_ID, DYS.NAME_DAY, ATT.ATTENDANCE_DATE,
        (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.IN_OUT = '1' ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) Entrada,
        (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.IN_OUT = '2' ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) Salida,
        (SELECT TIN.DESCRIP_TINC FROM admin_attendance ATE INNER JOIN code_incidence TIN ON ATE.TINC = TIN.CODE_TINC WHERE ATE.NOM_ID = ATT.NOM_ID AND ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.IN_OUT = '1' ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) DESCRIP_TINC,
        (SELECT ATE.JUSTIFY FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.IN_OUT = '1' ORDER BY ATE.JUSTIFY ASC LIMIT 1) Justify
    FROM admin_attendance ATT
    INNER JOIN code_days DYS ON DYS.CODE_DAY = ATT.CODE_DAY
    WHERE ATT.NOM_ID = '$user_active' AND ATT.ATTENDANCE_DATE BETWEEN 
        (SELECT PRP.START_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID')  AND (SELECT PRP.END_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID')
    ORDER BY ATT.ATTENDANCE_DATE ASC";

$sql_attendance_records = "SELECT DISTINCT REGS.ID, REGS.START_DATE_PP, REGS.END_DATE_PP, REGS.CALENDAR_DATE, REGS.CODE_DAY, REGS.NAME_DAY
, REGS.DAY_OF_REST, REGS.PERIOD_PAYROLL_ID, REGS.SCHEDULE, REGS.ID_NOM, REGS.NAME_EMP, REGS.JOB_NAME, REGS.AttendanceId
, REGS.Feriado, REGS.ENTRADA, REGS.REG_ENTRADA, REGS.DES_INCIDENCE, REGS.CODE_INCIDENC, REGS.SALIDA, REGS.REG_SALIDA, REGS.JUSTIFY
FROM (
    (SELECT
        PN.ID
        , PN.START_DATE START_DATE_PP
        , PN.END_DATE END_DATE_PP
        , CAL.YEAR
        , CAL.CALENDAR_DATE
        , CAL.WEEK
        , CAL.CODE_DAY
        , DAYS.NAME_DAY
        , CAL.DAY_OF_REST
        , CAL.PERIOD_PAYROLL_ID
        , HA.SCHEDULE
        , HA.ID_NOM
        , IFNULL(REG.AttendanceId, '') AttendanceId
        , (SELECT CONCAT(EMP.NAME,' ',EMP.LAST_NAME,' ',EMP.LAST_NAME_PREFIX) FROM employed EMP WHERE EMP.ID_NOM = HA.ID_NOM) NAME_EMP
        , (SELECT JOB.JOB_NAME FROM employed EMP INNER JOIN code_jobs JOB ON JOB.CODE_JOB = EMP.JOB WHERE EMP.ID_NOM = HA.ID_NOM) JOB_NAME
        , HA.START_DATE START_DATE_SH
        , HA.END_DATE END_DATE_SH
        , IF(CAL.DAY_OF_REST = 0, 'Laboral', 'Feriado') Feriado
        , IFNULL(HOR.TIME_START, '') ENTRADA
        , REG.ATTENDANCE_TIME REG_ENTRADA
        , IF(HOR.TIME_START IS NOT NULL AND REG.ATTENDANCE_TIME IS NULL AND CI.CODE_TINC IS NULL, 'FALTA INJUSTIFICADA', CI.DESCRIP_TINC) DES_INCIDENCE
        , IF(HOR.TIME_START IS NOT NULL AND REG.ATTENDANCE_TIME IS NULL AND CI.CODE_TINC IS NULL, 01, CI.CODE_TINC) CODE_INCIDENC
        , IFNULL(HOR.OUT_TIME, '') SALIDA
        , REG2.ATTENDANCE_TIME REG_SALIDA
        , REG.JUSTIFY JUSTIFY
    FROM 
        payroll_period PN
        INNER JOIN calendar CAL ON CAL.CALENDAR_DATE BETWEEN PN.START_DATE AND PN.END_DATE AND PN.ID = CAL.PERIOD_PAYROLL_ID
        LEFT OUTER JOIN assigned_schedule HA ON CAL.CALENDAR_DATE BETWEEN HA.START_DATE AND HA.END_DATE
        LEFT OUTER JOIN admin_schedules HOR ON HA.SCHEDULE = HOR.CODE_SCHEDULE AND CAL.CODE_DAY = HOR.CODE_DAY
        LEFT OUTER JOIN admin_attendance REG ON CAL.CALENDAR_DATE = REG.ATTENDANCE_DATE AND HA.ID_NOM = REG.NOM_ID
                                            AND CAL.CODE_DAY = REG.CODE_DAY AND REG.IN_OUT = 1
        LEFT OUTER JOIN admin_attendance REG2 ON CAL.CALENDAR_DATE = REG2.ATTENDANCE_DATE AND HA.ID_NOM = REG2.NOM_ID
                                            AND CAL.CODE_DAY = REG2.CODE_DAY AND REG2.IN_OUT = 2
        LEFT OUTER JOIN code_incidence CI ON REG.TINC = CI.CODE_TINC
        INNER JOIN code_days DAYS ON DAYS.CODE_DAY = CAL.CODE_DAY
    WHERE 
        PN.ID = '$payrollPeriodID'
        AND HA.ID_NOM = '$user_active'
        AND CAL.CALENDAR_DATE <= NOW())
    UNION
(SELECT
                            PN.ID
                            , PN.START_DATE START_DATE_PP
                            , PN.END_DATE END_DATE_PP
                            , CAL.YEAR
                            , CAL.CALENDAR_DATE
                            , CAL.WEEK
                            , CAL.CODE_DAY
                            , DAYS.NAME_DAY
                            , CAL.DAY_OF_REST
                            , CAL.PERIOD_PAYROLL_ID
                            , HA.SCHEDULE_GROUP
                            , HA.ID_NOM
                            , IFNULL(REG.AttendanceId, '') AttendanceId
                            , (SELECT CONCAT(EMP.NAME,' ',EMP.LAST_NAME,' ',EMP.LAST_NAME_PREFIX) FROM employed EMP WHERE EMP.ID_NOM = HA.ID_NOM) NAME_EMP
                            , (SELECT JOB.JOB_NAME FROM employed EMP INNER JOIN code_jobs JOB ON JOB.CODE_JOB = EMP.JOB WHERE EMP.ID_NOM = HA.ID_NOM) JOB_NAME
                            , '' START_DATE_SH
                            , '' END_DATE_SH
                            , IF(CAL.DAY_OF_REST = 0, 'Laboral', 'Feriado') Feriado
                            , IFNULL(HOR.TIME_START, '') ENTRADA
                            , REG.ATTENDANCE_TIME REG_ENTRADA
                            , IF(HOR.TIME_START IS NOT NULL AND REG.ATTENDANCE_TIME IS NULL AND CI.CODE_TINC IS NULL, 'FALTA INJUSTIFICADA', CI.DESCRIP_TINC) DES_INCIDENCE
                            , IF(HOR.TIME_START IS NOT NULL AND REG.ATTENDANCE_TIME IS NULL AND CI.CODE_TINC IS NULL, 01, CI.CODE_TINC) CODE_INCIDENC
                            , IFNULL(HOR.OUT_TIME, '') SALIDA
                            , REG2.ATTENDANCE_TIME REG_SALIDA 
                            , REG.JUSTIFY JUSTIFY
                            FROM 
                            payroll_period PN
                            INNER JOIN calendar CAL ON CAL.CALENDAR_DATE BETWEEN PN.START_DATE AND PN.END_DATE AND PN.ID = CAL.PERIOD_PAYROLL_ID
                            INNER JOIN employed HA ON HA.ID_NOM = '$user_active' 
                            LEFT OUTER JOIN admin_schedules HOR ON HA.SCHEDULE_GROUP = HOR.CODE_SCHEDULE AND CAL.CODE_DAY = HOR.CODE_DAY
                            LEFT OUTER JOIN admin_attendance REG ON CAL.CALENDAR_DATE = REG.ATTENDANCE_DATE AND HA.ID_NOM = REG.NOM_ID
                                            AND CAL.CODE_DAY = REG.CODE_DAY AND REG.IN_OUT = 1
                            LEFT OUTER JOIN admin_attendance REG2 ON CAL.CALENDAR_DATE = REG2.ATTENDANCE_DATE AND HA.ID_NOM = REG2.NOM_ID
                                            AND CAL.CODE_DAY = REG2.CODE_DAY AND REG2.IN_OUT = 2
                            LEFT OUTER JOIN code_incidence CI ON REG.TINC = CI.CODE_TINC
                            INNER JOIN code_days DAYS ON DAYS.CODE_DAY = CAL.CODE_DAY
                            WHERE PN.ID = '$payrollPeriodID' 
                            AND HA.ID_NOM = '$user_active'
                            AND CAL.CALENDAR_DATE <= NOW()
                            AND CONCAT(CAL.YEAR,'-',CAL.WEEK,'-',HA.ID_NOM) NOT IN (SELECT DISTINCT CONCAT(SHA.YEAR,'-',SHA.WEEK,'-',SHA.ID_NOM) FROM assigned_schedule SHA))
) AS REGS
ORDER BY REGS.CALENDAR_DATE, REGS.ID_NOM;";

/** Horario */

$sql_schedule = "SELECT * FROM employed EMP
    LEFT OUTER JOIN admin_schedules ADS ON ADS.CODE_SCHEDULE = EMP.SCHEDULE_GROUP
    INNER JOIN code_days DYS ON DYS.CODE_DAY = ADS.CODE_DAY
    WHERE EMP.ID_NOM = '$user_active';";

/** Validar qué estatus tendrá la asistencia del colaborador */
$sql_get_incidence = "SELECT DISTINCT EMP.ID_NOM
        , COALESCE(ASH.MIN_TIME_START, AS2.MIN_TIME_START) MIN_TIME_START
        , COALESCE(ASH.TIME_START, AS2.TIME_START) TIME_START
        , COALESCE(ASH.AUSENCE_TIME, AS2.AUSENCE_TIME) AUSENCE_TIME
        , COALESCE(ASH.MIN_TIME_OUT, AS2.MIN_TIME_OUT) MIN_TIME_OUT
        , COALESCE(ASH.LOCK_IN_TIME, AS2.LOCK_IN_TIME) LOCK_IN_TIME
        , COALESCE(ASH.OUT_TIME, AS2.OUT_TIME) OUT_TIME
        , COALESCE(ASH.DELAY_TIME_START, AS2.DELAY_TIME_START) DELAY_TIME_START
    FROM employed EMP 
    LEFT OUTER JOIN assigned_schedule AAS ON EMP.ID_NOM = AAS.ID_NOM AND DATE(NOW()) BETWEEN AAS.START_DATE AND AAS.END_DATE
    LEFT OUTER JOIN admin_schedules ASH ON ASH.CODE_SCHEDULE = AAS.SCHEDULE
    LEFT OUTER JOIN admin_schedules AS2 ON AS2.CODE_SCHEDULE = EMP.SCHEDULE_GROUP
    WHERE EMP.ID_NOM = '$user_active' AND COALESCE(ASH.CODE_DAY, AS2.CODE_DAY) = '$codeDay'";



/** Validar Retardos para Falta por Retardos */

$sql_countDelays = "SELECT
        AAT.ATTENDANCE_DATE,
        (SELECT DISTINCT ATE.TINC FROM admin_attendance ATE WHERE ATE.NOM_ID = AAT.NOM_ID AND ATE.ATTENDANCE_DATE = AAT.ATTENDANCE_DATE ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) TINC
    FROM admin_attendance AAT
    INNER JOIN payroll_period PRP ON AAT.ATTENDANCE_DATE BETWEEN PRP.START_DATE AND PRP.END_DATE
    INNER JOIN code_incidence INCI ON INCI.CODE_TINC = AAT.TINC
    WHERE '$getDate' BETWEEN PRP.START_DATE AND PRP.END_DATE AND INCI.DESCRIP_TINC IN ('FALTA POR RETARDOS','RETARDO') AND AAT.IN_OUT = 1 AND NOM_ID = '$user_active'
    ORDER BY AAT.ATTENDANCE_DATE";

/** Validar Retardos para Falta por Retardos */


/** Validar registros de Asistencia del día de hoy */
$sql_attendance_today = "SELECT 
    NAME_DAY, ATTENDANCE_DATE, COUNT(DISTINCT ATT.AttendanceID) CHECKS,
    IFNULL( (SELECT ATE.TINC FROM admin_attendance ATE  WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') TINC,
    IFNULL( (SELECT ATE.JUSTIFY FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.JUSTIFY DESC LIMIT 1), '') JUSTIFY,
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECKIN,
    IFNULL( (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.ATTENDANCE_DATE = ATT.ATTENDANCE_DATE AND ATE.NOM_ID = ATT.NOM_ID AND ATE.IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1), '') CHECKOUT
    FROM admin_attendance ATT
    INNER JOIN code_days DYS ON DYS.CODE_DAY = ATT.CODE_DAY
    WHERE NOM_ID = '$user_active' AND ATT.ATTENDANCE_DATE = '$getDate' LIMIT 1";

?>