<?php

$sqlUsers = "SELECT 
        DISTINCT USR.SICAVP_USER
        , CONCAT(ASH.NAME) NAME_DOC
        , CAL.LEVEL_DESCRIPTION
        , USR.SEPARATION_FLAG
        , USR.FLAG_CONFIRM
    FROM users USR 
    INNER JOIN academic_schedules ASH ON ASH.PERSON_CODE_ID = USR.SICAVP_USER
    INNER JOIN code_accesslevels CAL ON CAL.CODE_LEVEL = USR.ACCESS_LEVEL
    WHERE ACCESS_LEVEL = '4';";

?>