<?php
//Lista de Empleados
$sql_users = "SELECT DISTINCT USR.SICAVP_USER
        , CONCAT(EMP.NAME,' ',EMP.LAST_NAME,' ',EMP.LAST_NAME_PREFIX) EMP_NAME
        , EMP.GOVERNMENT_ID
        , SES.NOM_SESION
        , SES.CITY
        , ARE.NAME_AREA
        , DEP.DEPARTMENT
        , JBS.JOB_NAME
        , POS.POSITION_DESCRIPTION
        , PAY.DESCRIPTION PAYROLL
        , SCG.DESCRIPTION SCHEDULEGROUP
        , EMP.STATUS
        , USR.SEPARATION_FLAG
        , USR.ACCESS_LEVEL
        , ACL.LEVEL_DESCRIPTION
        , MAP.ID_BIOUNIVER
    FROM users USR
    LEFT OUTER JOIN employed EMP ON USR.SICAVP_USER = EMP.ID_NOM
    LEFT OUTER JOIN code_area ARE ON ARE.CODE_AREA = EMP.AREA
    LEFT OUTER JOIN code_department DEP ON DEP.CODE_DEPRTMENT = EMP.DEPARTMENT AND DEP.CODE_AREA = EMP.AREA
    LEFT OUTER JOIN code_position POS ON POS.CODE_POSITION = EMP.POSITION
    LEFT OUTER JOIN code_jobs JBS ON JBS.CODE_JOB = EMP.JOB
    LEFT OUTER JOIN code_sesion SES ON SES.CODE_SESION_NOM = USR.NOM_SESSION AND SES.CODE_CITY = USR.CITY
    LEFT OUTER JOIN code_payroll PAY ON PAY.CODE_PAYROLL = EMP.PAYROLL
    LEFT OUTER JOIN code_schedule_groups SCG ON SCG.CODE = EMP.SCHEDULE_GROUP
    LEFT OUTER JOIN mapping_bioadminemploy MAP ON MAP.ID_NOM2001 = USR.SICAVP_USER
    INNER JOIN code_accesslevels ACL ON ACL.CODE_LEVEL = USR.ACCESS_LEVEL
    WHERE USR.ACCESS_LEVEL != '4'
    ORDER BY EMP.ID_NOM ASC";

?>