<?php 

// Consulta para obtener la tabla del historial de asistencias de los empleados (INCOMPLETA, El complemento WHERE veiene en el código biweekly.php)
$sql_paryrollPeriod_report = "SELECT DISTINCT CAL.CALENDAR_DATE
	, DYS.NAME_DAY
	, SCHE.CODE_SCHEDULE
    , CONCAT(SCHE.ID_NOM,' - ',SCHE.NAME,' ',SCHE.LAST_NAME,' ',SCHE.LAST_NAME_PREFIX) NAME_EMP
    , ATN.TINC
    , SCHE.JOB_NAME
    , ADS.TIME_START
    , ADS.OUT_TIME
    , CIN.DESCRIP_TINC
    , ATN.CHECK_IN
    , ATN.CHECK_OUT
    , SCHE.SUPERVISOR_ID
FROM calendar CAL 
INNER JOIN code_days DYS ON DYS.CODE_DAY = CAL.CODE_DAY
INNER JOIN admin_schedules ASD ON CAL.CODE_DAY = ASD.CODE_DAY
LEFT OUTER JOIN (
    SELECT * FROM (
        SELECT DISTINCT 
            DYS2.CODE_DAY, DYS2.NAME_DAY, EMP.ID_NOM, 
            EMP.NAME, EMP.LAST_NAME, EMP.LAST_NAME_PREFIX, 
            ASH.CODE_SCHEDULE, JBS.JOB_NAME, EMP.SUPERVISOR_ID,
            ROW_NUMBER() OVER (PARTITION BY EMP.ID_NOM, DYS2.CODE_DAY ORDER BY ASH.CODE_SCHEDULE DESC) AS RN
        FROM employed EMP
        LEFT OUTER JOIN assigned_schedule ASIG ON ASIG.ID_NOM = EMP.ID_NOM  
        INNER JOIN admin_schedules ASH ON ASH.CODE_SCHEDULE = COALESCE(ASIG.SCHEDULE, EMP.SCHEDULE_GROUP)  
        INNER JOIN code_days DYS2 ON DYS2.CODE_DAY = ASH.CODE_DAY  
        INNER JOIN code_jobs JBS ON JBS.CODE_JOB = EMP.JOB
        WHERE EMP.SUPERVISOR_ID = '$user_active'
            AND (EMP.STATUS = 'A' OR EMP.SEPARATION_DATE < (SELECT PRP.END_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID'))
    ) AS Sub
    WHERE RN = 1  -- 🔥 Nos quedamos solo con un horario por día y empleado
) SCHE 
ON SCHE.CODE_DAY = CAL.CODE_DAY 
AND SCHE.CODE_SCHEDULE = ASD.CODE_SCHEDULE 
AND EXISTS (  
    SELECT 1 FROM assigned_schedule ASIG  
    WHERE ASIG.ID_NOM = SCHE.ID_NOM 
    AND CAL.CALENDAR_DATE BETWEEN ASIG.START_DATE AND ASIG.END_DATE  
)
LEFT OUTER JOIN (SELECT DISTINCT EML.ID_NOM
        , ATT.ATTENDANCE_DATE
        , (SELECT ATE.TINC FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATT.ATTENDANCE_DATE = ATE.ATTENDANCE_DATE AND IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) TINC
        , (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATT.ATTENDANCE_DATE = ATE.ATTENDANCE_DATE AND IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) CHECK_IN
        , (SELECT ATE.ATTENDANCE_TIME FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATT.ATTENDANCE_DATE = ATE.ATTENDANCE_DATE AND IN_OUT = 2 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) CHECK_OUT
    FROM employed EML
    LEFT OUTER JOIN admin_attendance ATT ON ATT.NOM_ID = EML.ID_NOM    
    WHERE EML.SUPERVISOR_ID = '$user_active' AND 
            (EML.STATUS = 'A' OR EML.SEPARATION_DATE >= (SELECT PRP.START_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID'))
            AND ((SELECT PRP.START_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID') > EML.ADMISSION_DATE ) ) AS ATN ON ATN.ID_NOM = SCHE.ID_NOM AND ATN.ATTENDANCE_DATE = CAL.CALENDAR_DATE
LEFT OUTER JOIN code_incidence CIN ON CIN.CODE_TINC = ATN.TINC
LEFT OUTER JOIN admin_schedules ADS ON ADS.CODE_SCHEDULE = SCHE.CODE_SCHEDULE AND ADS.CODE_DAY = CAL.CODE_DAY
WHERE CAL.CALENDAR_DATE BETWEEN (SELECT PRP.START_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID') 
    AND (SELECT PRP.END_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID') AND SCHE.SUPERVISOR_ID = '$user_active'
ORDER BY CAL.CALENDAR_DATE, NAME_EMP ASC;";

$sql_attendance_employed = "SELECT 
        EMP.JOB, EMP.ID_NOM ID, EMP.LAST_NAME, EMP.LAST_NAME_PREFIX, EMP.NAME,
        (SELECT ATT.AttendanceId FROM admin_attendance ATT WHERE ATT.NOM_ID = EMP.ID_NOM AND ATT.IN_OUT = '1' AND ATT.ATTENDANCE_DATE = '$selectedDate') ATTENDANCE,
        (SELECT ATT.ATTENDANCE_TIME FROM admin_attendance ATT WHERE ATT.NOM_ID = EMP.ID_NOM AND ATT.IN_OUT = '1' AND ATT.ATTENDANCE_DATE = '$selectedDate') ENTRADA,
        (SELECT ATT.TINC FROM admin_attendance ATT WHERE ATT.NOM_ID = EMP.ID_NOM AND ATT.IN_OUT = '1' AND ATT.ATTENDANCE_DATE = '$selectedDate') TINC,
        (SELECT INC.DESCRIP_TINC FROM admin_attendance ATT LEFT OUTER JOIN code_incidence INC ON INC.CODE_TINC = ATT.TINC WHERE ATT.NOM_ID = EMP.ID_NOM AND ATT.IN_OUT = '1' AND ATT.ATTENDANCE_DATE = '$selectedDate') TINC_N,
        (SELECT ATT.COMMENTS FROM admin_attendance ATT WHERE ATT.NOM_ID = EMP.ID_NOM AND ATT.IN_OUT = '1' AND ATT.ATTENDANCE_DATE = '$selectedDate') COMMENTS,
        (SELECT ATT.JUSTIFY FROM admin_attendance ATT WHERE ATT.NOM_ID = EMP.ID_NOM AND ATT.IN_OUT = '1' AND ATT.ATTENDANCE_DATE = '$selectedDate') JUSTIFY
    FROM employed EMP
    WHERE (EMP.SUPERVISOR_ID = '$user_active' OR EMP.SUPERVISOR_ID_AUX = '$user_active') AND STATUS = 'A'
    ORDER BY EMP.ID_NOM ASC"; 

//Reporte Excel

$sql_payrollPeriod_calendar = "SELECT 
    DISTINCT
        CAL.CALENDAR_DATE
    FROM calendar CAL
    INNER JOIN payroll_period PRP ON CAL.CALENDAR_DATE BETWEEN PRP.START_DATE AND PRP.END_DATE
    WHERE PRP.ID = '$payrollPeriodID'";

$sql_payrollPeriod = "SELECT PRP.DESCRIPTION, PRP.START_DATE FROM payroll_period PRP WHERE PRP.ID = '$payrollPeriodID'";

$sql_getAbsences = "SELECT DISTINCT
    EMP.INSTITUTION, EMP.ID_NOM, ATT.ATTENDANCE_DATE, EMP.PAYROLL,
    (SELECT ATE.TINC FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATT.ATTENDANCE_DATE = ATE.ATTENDANCE_DATE AND IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) TINC
    FROM admin_attendance ATT
    INNER JOIN employed EMP ON EMP.ID_NOM = ATT.NOM_ID
    WHERE ATT.ATTENDANCE_DATE BETWEEN (SELECT START_DATE FROM payroll_period PRP WHERE ID = '$payrollPeriodID') AND (SELECT END_DATE FROM payroll_period PRP WHERE ID = '$payrollPeriodID') 
    AND (EMP.SUPERVISOR_ID = '$user_active' OR EMP.SUPERVISOR_ID_AUX = '$user_active')
    AND (SELECT ATE.TINC FROM admin_attendance ATE WHERE ATE.NOM_ID = ATT.NOM_ID AND ATT.ATTENDANCE_DATE = ATE.ATTENDANCE_DATE AND IN_OUT = 1 ORDER BY ATE.ATTENDANCE_TIME ASC LIMIT 1) 
        IN (SELECT DISTINCT CI.CODE_TINC FROM code_incidence CI WHERE CI.DESCRIP_TINC IN ('FALTA INJUSTIFICADA','FALTA POR RETARDOS','PERMISO SIN GOCE','SUSPENSION'))
    ORDER BY ATT.ATTENDANCE_DATE, ATT.NOM_ID ASC;";

?>