<?php 

$codeDayCheck = date('w');
//$codeDayCheck = '1';
//$codeDayCheck = '5';
$today = date('Y-m-d');

/** Módulo Asistencias */

//Horarios
$sql_academic_schedules_b = "SELECT 
        DISTINCT 
        ASH.EVENT, ASH.ROOM,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '1') START_MONDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '2') START_TUESDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '3') START_WEDNESDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '4') START_THURSDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '5') START_FRIDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '6') START_SATURDAY,
        (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '0') START_SUNDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '1') END_MONDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '2') END_TUESDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '3') END_WEDNESDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '4') END_THURSDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '5') END_FRIDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '6') END_SATURDAY,
        (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT = ASH.EVENT AND SCH.SessionPeriodId = ACL.SessionPeriodId AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM = ASH.ROOM AND SCH.START_CLASS = ASH.START_CLASS AND SCH.CODE_DAY = '0') END_SUNDAY
    FROM academic_schedules ASH
    INNER JOIN academic_calendar ACL ON ACL.SessionPeriodId = ASH.SessionPeriodId
    WHERE ASH.PERSON_CODE_ID = '$user_active'
        AND ACL.START_DATE <= '$today' AND ACL.END_DATE >= '$today'";

$sql_academic_schedules = "SELECT DISTINCT ASH.ROOM_NAME
	, ASH.PUBLICATION_NAME_1
    , ASH.SECTION
    , ASH.SERIAL_ID
    , ASH.START_DATE
    , ASH.END_DATE
    , CSP.LONG_DESC SESION_PWC
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '1' limit 1) START_MONDAY
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '2' limit 1) START_TUESDAY
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '3' limit 1) START_WEDNESDAY
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '4' limit 1) START_THURSDAY
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '5' limit 1) START_FRIDAY
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '6' limit 1) START_SATURDAY
    , (SELECT DISTINCT SCH.START_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '0' limit 1) START_SUNDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '1' limit 1) END_MONDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '2' limit 1) END_TUESDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '3' limit 1) END_WEDNESDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '4' limit 1) END_THURSDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '5' limit 1) END_FRIDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '6' limit 1) END_SATURDAY
    , (SELECT DISTINCT SCH.END_CLASS FROM academic_schedules SCH WHERE SCH.EVENT_ID = ASH.EVENT_ID AND SCH.PERSON_CODE_ID = ASH.PERSON_CODE_ID AND SCH.ROOM_ID = ASH.ROOM_ID AND SCH.CODE_DAY AND SCH.ACADEMIC_SESSION = ASH.ACADEMIC_SESSION and SCH.CODE_DAY = '0' limit 1) END_SUNDAY
FROM academic_schedules ASH
LEFT OUTER JOIN code_sesion_academic CSP ON CSP.CODE_VALUE_KEY = ASH.ACADEMIC_SESSION
WHERE ASH.PERSON_CODE_ID = '$user_active'
	AND DATE(NOW()) BETWEEN ASH.START_DATE AND ASH.END_DATE
ORDER BY ASH.CODE_DAY, ASH.START_CLASS;";

//Check in - Check out
$sql_academic_check = "SELECT DISTINCT ASH.PK
    , ASH.PERSON_CODE_ID ID
    , ASH.CODE_DAY DY
    , ASH.ACADEMIC_SESSION SESION
    , ASH.PROGRAM_DESC
    , ASH.PROGRAM
    , ASH.CURRICULUM
    , ASH.FORMAL_TITLE
    , ASH.ROOM_NAME 
    , ASH.ROOM_ID ROOM
    , ASH.EVENT_ID
    , ASH.PUBLICATION_NAME_1 MAT
    , ASH.MAX_BEFORE_CLASS
    , ASH.START_CLASS
    , ASH.DELAY_CLASS
    , ASH.MAX_DELAY_CLASS
    , ASH.MIN_END_CLASS
    , ASH.END_CLASS
    , ASH.ACADEMIC_TERM
    , IFNULL( (SELECT DISTINCT ATT.ATTENDANCE_DATE FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.EVENT_ID = ATT.EVENT_ID AND ASH.PROGRAM = ATT.PROGRAM AND ASH.CURRICULUM = ATT.CURRICULUM AND ATT.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE AND ATT.ROOM_ID = ASH.ROOM_ID AND ATT.GENERAL_ED = ASH.GENERAL_ED AND ATT.SECTION = ASH.SECTION AND ATT.SERIAL_ID = ASH.SERIAL_ID AND ATT.ATTENDANCE_DATE = DATE(NOW())), '') ATTENDANCE_DATE
    , IFNULL( (SELECT DISTINCT ATT.TINC FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.EVENT_ID = ATT.EVENT_ID AND ASH.PROGRAM = ATT.PROGRAM AND ASH.CURRICULUM = ATT.CURRICULUM AND ATT.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE AND ATT.ROOM_ID = ASH.ROOM_ID AND ATT.GENERAL_ED = ASH.GENERAL_ED AND ATT.SECTION = ASH.SECTION AND ATT.SERIAL_ID = ASH.SERIAL_ID AND ATT.ATTENDANCE_DATE = DATE(NOW()) AND ATT.IN_OUT = 1 ORDER BY AttendanceId ASC LIMIT 1), '') TINC
    , IFNULL( (SELECT DISTINCT ATT.ATTENDANCE_TIME FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.EVENT_ID = ATT.EVENT_ID AND ASH.PROGRAM = ATT.PROGRAM AND ASH.CURRICULUM = ATT.CURRICULUM AND ATT.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE AND ATT.ROOM_ID = ASH.ROOM_ID AND ATT.GENERAL_ED = ASH.GENERAL_ED AND ATT.SECTION = ASH.SECTION AND ATT.SERIAL_ID = ASH.SERIAL_ID AND ATT.ATTENDANCE_DATE = DATE(NOW()) AND ATT.IN_OUT = 1 ORDER BY AttendanceId ASC LIMIT 1), '') CHECK_IN
    , IFNULL( (SELECT DISTINCT ATT.ATTENDANCE_TIME FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.EVENT_ID = ATT.EVENT_ID AND ASH.PROGRAM = ATT.PROGRAM AND ASH.CURRICULUM = ATT.CURRICULUM AND ATT.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE AND ATT.ROOM_ID = ASH.ROOM_ID AND ATT.GENERAL_ED = ASH.GENERAL_ED AND ATT.SECTION = ASH.SECTION AND ATT.SERIAL_ID = ASH.SERIAL_ID AND ATT.ATTENDANCE_DATE = DATE(NOW())  AND ATT.IN_OUT = 2 ORDER BY AttendanceId ASC LIMIT 1), '') CHECK_OUT
    , IFNULL( (SELECT DISTINCT ATT.CLASS_SUMMARY FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.EVENT_ID = ATT.EVENT_ID AND ASH.PROGRAM = ATT.PROGRAM AND ASH.CURRICULUM = ATT.CURRICULUM AND ATT.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE AND ATT.ROOM_ID = ASH.ROOM_ID AND ATT.GENERAL_ED = ASH.GENERAL_ED AND ATT.SECTION = ASH.SECTION AND ATT.SERIAL_ID = ASH.SERIAL_ID AND ATT.ATTENDANCE_DATE = DATE(NOW())  AND ATT.IN_OUT = 1  ORDER BY AttendanceId ASC LIMIT 1), '') CLASS_SUMMARY
    , IFNULL( (SELECT DISTINCT ATT.JUSTIFY FROM academic_attendance ATT WHERE ASH.PERSON_CODE_ID = ATT.ACADEMIC_ID AND ASH.CODE_DAY = ATT.CODE_DAY AND ASH.EVENT_ID = ATT.EVENT_ID AND ASH.PROGRAM = ATT.PROGRAM AND ASH.CURRICULUM = ATT.CURRICULUM AND ATT.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE AND ATT.ROOM_ID = ASH.ROOM_ID AND ATT.GENERAL_ED = ASH.GENERAL_ED AND ATT.SECTION = ASH.SECTION AND ATT.SERIAL_ID = ASH.SERIAL_ID AND ATT.ATTENDANCE_DATE = DATE(NOW())  AND ATT.IN_OUT = 1  ORDER BY AttendanceId ASC LIMIT 1), '') JUSTIFY 
FROM academic_schedules ASH 
WHERE ASH.PERSON_CODE_ID = '$user_active' 
    AND DATE(NOW()) BETWEEN ASH.START_DATE AND ASH.END_DATE
    AND CODE_DAY = '$codeDayCheck' AND ASH.FLAG_CLINIC = '$flagClinic'
ORDER BY CHECK_OUT ASC, CHECK_IN DESC, ASH.START_CLASS ASC;";

$sql_get_attendance = "SELECT DISTINCT
        DYS.NAME_DAY, ATD.ATTENDANCE_DATE, ATD.PROGRAM, ATD.CURRICULUM, ATD.EVENT_ID, ATD.ROOM_ID, ATD.SECTION, ATD.SERIAL_ID, ASH.FORMAL_TITLE, ASH.PROGRAM_DESC, ASH.PUBLICATION_NAME_1, ASH.ROOM_NAME,
        (SELECT TIN.DESCRIP_TINC FROM academic_attendance DAT INNER JOIN code_incidence TIN ON TIN.CODE_TINC = DAT.TINC WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 1 ORDER BY DAT.ATTENDANCE_TIME DESC LIMIT 1) DESCRIP_TINC,
        (SELECT DAT.ATTENDANCE_TIME FROM academic_attendance DAT WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 1 ORDER BY DAT.ATTENDANCE_TIME DESC LIMIT 1) CHECK_IN,
        (SELECT DAT.ATTENDANCE_TIME FROM academic_attendance DAT WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 2 ORDER BY DAT.ATTENDANCE_TIME DESC LIMIT 1) CHECK_OUT,
        (SELECT DAT.JUSTIFY FROM academic_attendance DAT WHERE DAT.SCHEDULE_ID = ATD.SCHEDULE_ID AND DAT.ATTENDANCE_DATE = ATD.ATTENDANCE_DATE AND DAT.IN_OUT = 1  ORDER BY DAT.JUSTIFY DESC LIMIT 1) JUSTIFY
    FROM academic_attendance ATD 
    INNER JOIN code_days DYS ON DYS.CODE_DAY = ATD.CODE_DAY
    INNER JOIN academic_schedules ASH ON ASH.PERSON_CODE_ID = ATD.ACADEMIC_ID AND ASH.CODE_DAY = ATD.CODE_DAY AND ASH.EVENT_ID = ATD.EVENT_ID AND ASH.PROGRAM = ATD.PROGRAM AND ASH.CURRICULUM = ATD.CURRICULUM AND (ATD.ATTENDANCE_DATE BETWEEN ASH.START_DATE AND ASH.END_DATE) AND ATD.ROOM_ID = ASH.ROOM_ID AND ATD.GENERAL_ED = ATD.GENERAL_ED AND ATD.START_CLASS = ASH.START_CLASS
    WHERE ATD.ACADEMIC_ID = '$user_active' AND ATD.ATTENDANCE_DATE BETWEEN (SELECT PRP.START_DATE FROM payroll_period PRP WHERE ID = '$payrollPeriodID') AND (SELECT PRP.END_DATE FROM payroll_period PRP WHERE ID = '$payrollPeriodID')
    ORDER BY ATD.ATTENDANCE_DATE ASC, CHECK_IN ASC";

$sql_countDelays = "SELECT DISTINCT AAT.EVENT_ID, COUNT(AAT.TINC) TINC
    FROM academic_attendance AAT
    INNER JOIN payroll_period PRP ON AAT.ATTENDANCE_DATE BETWEEN PRP.START_DATE AND PRP.END_DATE
    WHERE date(now()) BETWEEN PRP.START_DATE AND PRP.END_DATE AND AAT.TINC IN (22,02) AND AAT.IN_OUT = 1 AND AAT.ACADEMIC_ID = '$user_active'
    GROUP BY AAT.EVENT_ID;";

?>